### PR TITLE
added Chinese

### PR DESCRIPTION
**Pull request by JiangLongLiu**
Thanks for sending a pull request! Please review the [guidelines for contributing](CONTRIBUTING.md), then fill out the blanks below.

What does this implement/fix? Explain your changes
--------------------------------------------------
…

Does this close any currently open issues?
------------------------------------------
…

Any other comments?
-------------------
…

### CODE REVIEW

**Comment by AntonyCorbett** [comment]
@JiangLongLiu Thanks for your work on this translation. The contributing.md file refers to localisation, which we manage using the Crowdin platform:

https://github.com/AntonyCorbett/OnlyR/blob/master/CONTRIBUTING.md#localisation

**Comment by JiangLongLiu** [comment]
> translator

Of course I can, I'd love to be a translator
Thanks for writing this excellent tool, I'm using it at the moment.

**Comment by AntonyCorbett** [comment]
@JiangLongLiu I have added the Chinese language to OnlyR and included your translations from this PR. It should be available in a new release soon. Please send me your Crowdin name (or sign up on Crowdin.com and request access to the OnlyR project) so that you can manage the Chinese translation.

**Comment by JiangLongLiu** [comment]
Okay, I'll operate it later. Thank you!

Antony Corbett ***@***.***> 于 2023年3月31日周五 下午7:56写道：

**Comment by JiangLongLiu** [comment]
> @JiangLongLiu I have added the Chinese language to OnlyR and included your translations from this PR. It should be available in a new release soon. Please send me your Crowdin name (or sign up on Crowdin.com and request access to the OnlyR project) so that you can manage the Chinese translation.

My crowdin.com username is liujianglong, thank you

**Pull request closed without merging**
